from SpecImports import *
LobbyParent = 10014
BoilerParent = 10030
PipeLeftParent = 10023
PipeRightParent = 10032
OilParent = 10034
ControlParent = 10037
DuctParent = 10036
PaintMixerStorageParent = 10660
EastCatwalkParent = 10661
WestCatwalkParent = 10662
CenterSiloOutsideBattleCellParent = 10663
CenterSiloOutsideBattleSet2Parent = 10663
CenterSiloBattleCellParent = 10064
CenterSiloParent = 20095
SigRoomParent = 20058
WestSiloParent = 20094
WestSiloBattleCellParent = 10047
EastSiloParent = 20096
EastSiloBattleCellParent = 10068
LobbyHallwayParent = 40000
StomperAlleyParent = 40001
LavaRewardRoomParent = 40002
LavaRoomFoyerParent = 40003
WestSiloControlRoomParent = 40004
EastSiloControlRoomParent = 40005
WarehouseMainFloorParent = 40006
GearRoomSet2Parent = 40007
PipeFrontParent = 40009
PipeBackParent = 40010
LobbySet2Parent = 40011
LobbyRightParent = 40012
LobbyLeftParent = 40013
WarehouseLookoutParent = 40014
WestCatwalkSet1Parent = 40015
WarehouseWestParent = 40016
WarehouseEastParent = 40017
OutsidePaintMixerParent = 40018
BoilerRoomSet2Parent = 40019
OutsidePipeRoomParent = 40020
OilRoomHallway1Parent = 40021
OilRoomHallway2Parent = 40022
SideEntranceParent = 40023
EntranceParent = 40024
LobbyCell = 0
BoilerCell = 1
PipeLeftCell = 2
PipeRightCell = 3
OilCell = 4
ControlCell = 5
DuctCell = 6
CenterSiloCell = 7
SigRoomCell = 8
WestSiloCell = 9
EastSiloCell = 10
CenterSiloOutsideCell = 11
PaintMixerStorageCell = 12
EastCatwalkCell = 13
WestCatwalkCell = 14
LobbyHallwayCell = 15
StomperAlleyCell = 16
LavaRewardRoomCell = 17
LavaRoomFoyerCell = 18
WestSiloControlRoomCell = 19
EastSiloControlRoomCell = 20
WarehouseMainFloorCell = 21
GearRoomSet2Cell = 22
CenterSiloOutsideBattleSet2Cell = 23
PipeFrontCell = 24
PipeBackCell = 25
LobbySet2Cell = 26
LobbyRightSet1Cell = 27
LobbyRightSet2Cell = 28
UnusedCellA = 29
LobbyLeftSet1Cell = 30
LobbyLeftSet2Cell = 31
UnusedCellB = 32
WarehouseLookoutCell = 33
WestCatwalkSet1Cell = 34
UnusedCellC = 35
WarehouseEastCell = 36
OutsidePaintMixerCell = 37
BoilerRoomSet2Cell = 38
OutsidePipeRoomCell = 39
OilRoomHallway1Cell = 40
OilRoomHallway2Cell = 41
SideEntranceCell = 42
EntranceCell = 43
BattleCells = {LobbyCell: {'parentEntId': LobbyParent,
             'pos': Point3(0, 0, 0)},
 BoilerCell: {'parentEntId': BoilerParent,
              'pos': Point3(0, 0, 0)},
 OilCell: {'parentEntId': OilParent,
           'pos': Point3(0, 0, 0)},
 ControlCell: {'parentEntId': ControlParent,
               'pos': Point3(0, 0, 0)},
 CenterSiloCell: {'parentEntId': CenterSiloBattleCellParent,
                  'pos': Point3(0, 0, 0)},
 PipeLeftCell: {'parentEntId': PipeLeftParent,
                'pos': Point3(0, 0, 0)},
 PipeRightCell: {'parentEntId': PipeRightParent,
                 'pos': Point3(0, 0, 0)},
 DuctCell: {'parentEntId': DuctParent,
            'pos': Point3(0, 0, 0)},
 SigRoomCell: {'parentEntId': SigRoomParent,
               'pos': Point3(0, 0, 0)},
 WestSiloCell: {'parentEntId': WestSiloBattleCellParent,
                'pos': Point3(0, 0, 0)},
 EastSiloCell: {'parentEntId': EastSiloBattleCellParent,
                'pos': Point3(-20, -10, 0)},
 CenterSiloOutsideCell: {'parentEntId': CenterSiloOutsideBattleCellParent,
                'pos': Point3(0, 0, 0)},
 PaintMixerStorageCell: {'parentEntId': PaintMixerStorageParent,
                'pos': Point3(0, 0, 0)},
 EastCatwalkCell: {'parentEntId': EastCatwalkParent,
                'pos': Point3(0, 0, 0)},
 WestCatwalkCell: {'parentEntId': WestCatwalkParent,
                'pos': Point3(0, 0, 0)},
 LobbyHallwayCell: {'parentEntId': LobbyHallwayParent,
                'pos': Point3(0, 0, 0)},
 StomperAlleyCell: {'parentEntId': StomperAlleyParent,
                'pos': Point3(0, 0, 0)},
 LavaRewardRoomCell: {'parentEntId': LavaRewardRoomParent,
                'pos': Point3(0, 0, 0)},
 LavaRoomFoyerCell: {'parentEntId': LavaRoomFoyerParent,
                'pos': Point3(0, 0, 0)},
 WestSiloControlRoomCell: {'parentEntId': WestSiloControlRoomParent,
                'pos': Point3(0, 0, 0)},
 EastSiloControlRoomCell: {'parentEntId': EastSiloControlRoomParent,
                'pos': Point3(0, 0, 0)},
 WarehouseMainFloorCell: {'parentEntId': WarehouseMainFloorParent,
                'pos': Point3(0, 0, 0)},
 GearRoomSet2Cell: {'parentEntId': GearRoomSet2Parent,
                'pos': Point3(0, 0, 0)},
 CenterSiloOutsideBattleSet2Cell: {'parentEntId': CenterSiloOutsideBattleSet2Parent,
                'pos': Point3(0, 0, 0)},
 PipeFrontCell: {'parentEntId': PipeFrontParent,
                'pos': Point3(0, 0, 0)},
 PipeBackCell: {'parentEntId': PipeBackParent,
                'pos': Point3(0, 0, 0)},
 LobbySet2Cell: {'parentEntId': LobbySet2Parent,
                'pos': Point3(0, 0, 0)},
 LobbyRightSet1Cell: {'parentEntId': LobbyRightParent,
                'pos': Point3(0, 0, 0)},
 LobbyRightSet2Cell: {'parentEntId': LobbyRightParent,
                'pos': Point3(0, 0, 0)},
 UnusedCellA: {'parentEntId': LobbyRightParent,
                'pos': Point3(0, 0, 0)},
 LobbyLeftSet1Cell: {'parentEntId': LobbyLeftParent,
                'pos': Point3(0, 0, 0)},
 LobbyLeftSet2Cell: {'parentEntId': LobbyLeftParent,
                'pos': Point3(0, 0, 0)},
 UnusedCellB: {'parentEntId': LobbyLeftParent,
                'pos': Point3(0, 0, 0)},
 WarehouseLookoutCell: {'parentEntId': WarehouseLookoutParent,
                'pos': Point3(0, 0, 0)},
 WestCatwalkSet1Cell: {'parentEntId': WestCatwalkSet1Parent,
                'pos': Point3(0, 0, 0)},
 UnusedCellC: {'parentEntId': WarehouseWestParent,
                'pos': Point3(0, 0, 0)},
 WarehouseEastCell: {'parentEntId': WarehouseEastParent,
                'pos': Point3(0, 0, 0)},
 OutsidePaintMixerCell: {'parentEntId': OutsidePaintMixerParent,
                'pos': Point3(0, 0, 0)},
 BoilerRoomSet2Cell: {'parentEntId': BoilerRoomSet2Parent,
                'pos': Point3(0, 0, 0)},
 OutsidePipeRoomCell: {'parentEntId': OutsidePipeRoomParent,
                'pos': Point3(0, 0, 0)},
 OilRoomHallway1Cell: {'parentEntId': OilRoomHallway1Parent,
                'pos': Point3(0, 0, 0)},
 OilRoomHallway2Cell: {'parentEntId': OilRoomHallway2Parent,
                'pos': Point3(0, 0, 0)},
 SideEntranceCell: {'parentEntId': SideEntranceParent,
                'pos': Point3(0, 0, 0)},
 EntranceCell: {'parentEntId': EntranceParent,
                'pos': Point3(0, 0, 0)}}
CogData = [{'type': 'm',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyCell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {'type': 'tf',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyCell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyCell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {'type': 'tf',
  'parentEntId': LobbyParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 10,
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20076,
  'skeleton': 0,
  'revives': 1},
 {'type': 'm',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 11,
  'battleCell': BoilerCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'walk',
  'path': 20077,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': BoilerParent,
  'boss': 0,
  'level': 11,
  'battleCell': BoilerCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'm',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 9,
  'battleCell': OilCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60133,
  'skeleton': 0,
  'revives': 1},
 {'type': 'nd',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 11,
  'battleCell': OilCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60134,
  'skeleton': 0,
  'revives': 1},
 {'type': 'nd',
  'parentEntId': OilParent,
  'boss': 0,
  'level': 11,
  'battleCell': OilCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 60135,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 10,
  'battleCell': ControlCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20039,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 11,
  'battleCell': ControlCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20049,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': ControlParent,
  'boss': 0,
  'level': 11,
  'battleCell': ControlCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20075,
  'skeleton': 0,
  'revives': 1},
 {'type': 'mh',
  'parentEntId': CenterSiloParent,
  'boss': 1,
  'level': 14,
  'battleCell': CenterSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 4},
 {'type': 'm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 12,
  'battleCell': CenterSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20103,
  'skeleton': 0,
  'revives': 3},
 {'type': 'tf',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 12,
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20104,
  'skeleton': 0,
  'revives': 2},
 {'type': 'm',
  'parentEntId': CenterSiloParent,
  'boss': 0,
  'level': 12,
  'battleCell': CenterSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20105,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestSiloCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20097,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20098,
  'skeleton': 0,
  'revives': 1},
 {'type': 'm',
  'parentEntId': WestSiloParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20099,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastSiloCell,
  'pos': Point3(0, -5, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20100,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastSiloCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20101,
  'skeleton': 0,
  'revives': 1},
 {'type': 'm',
  'parentEntId': EastSiloParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastSiloCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20102,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeLeftCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeLeftCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': PipeLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeLeftCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1}, 
 {'type': 'ms',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeRightCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'nd',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeRightCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': PipeRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeRightCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'mh',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 9,
  'battleCell': DuctCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20038,
  'skeleton': 0,
  'revives': 1},
 {'type': 'mh',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 10,
  'battleCell': DuctCell,
  'pos': Point3(10, 0, 0),
  'h': 0,
  'behavior': 'chase',
  'path': 20067,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': DuctParent,
  'boss': 0,
  'level': 11,
  'battleCell': DuctCell,
  'pos': Point3(-10, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': 20068,
  'skeleton': 0,
  'revives': 1},
 {'type': 'm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': SigRoomCell,
  'pos': Point3(5, -10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': SigRoomCell,
  'pos': Point3(5, -3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'm',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': SigRoomCell,
  'pos': Point3(5, 3.25, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': SigRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': SigRoomCell,
  'pos': Point3(5, 10.75, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': PaintMixerStorageParent,
  'boss': 0,
  'level': 9,
  'battleCell': PaintMixerStorageCell,
  'pos': Point3(5, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': PaintMixerStorageParent,
  'boss': 0,
  'level': 9,
  'battleCell': PaintMixerStorageCell,
  'pos': Point3(-5, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': EastCatwalkParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastCatwalkCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'ms',
  'parentEntId': EastCatwalkParent,
  'boss': 0,
  'level': 8,
  'battleCell': EastCatwalkCell,
  'pos': Point3(0, -5, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': WestCatwalkParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestCatwalkCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'ms',
  'parentEntId': WestCatwalkParent,
  'boss': 0,
  'level': 8,
  'battleCell': WestCatwalkCell,
  'pos': Point3(0, -5, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': LobbyHallwayParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyHallwayCell,
  'pos': Point3(0, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': StomperAlleyParent,
  'boss': 0,
  'level': 9,
  'battleCell': StomperAlleyCell,
  'pos': Point3(0, 3, 0),
  'h': 270,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': StomperAlleyParent,
  'boss': 0,
  'level': 9,
  'battleCell': StomperAlleyCell,
  'pos': Point3(0, -3, 0),
  'h': 270,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': LavaRewardRoomParent,
  'boss': 0,
  'level': 9,
  'battleCell': LavaRewardRoomCell,
  'pos': Point3(5, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': LavaRewardRoomParent,
  'boss': 0,
  'level': 9,
  'battleCell': LavaRewardRoomCell,
  'pos': Point3(-5, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': LavaRoomFoyerParent,
  'boss': 0,
  'level': 11,
  'battleCell': LavaRoomFoyerCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': LavaRoomFoyerParent,
  'boss': 0,
  'level': 11,
  'battleCell': LavaRoomFoyerCell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': LavaRoomFoyerParent,
  'boss': 0,
  'level': 11,
  'battleCell': LavaRoomFoyerCell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': LavaRoomFoyerParent,
  'boss': 0,
  'level': 11,
  'battleCell': LavaRoomFoyerCell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': WestSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestSiloControlRoomCell,
  'pos': Point3(-6, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': WestSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestSiloControlRoomCell,
  'pos': Point3(-2, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': WestSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestSiloControlRoomCell,
  'pos': Point3(2, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': WestSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': WestSiloControlRoomCell,
  'pos': Point3(6, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': EastSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastSiloControlRoomCell,
  'pos': Point3(-6, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': EastSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastSiloControlRoomCell,
  'pos': Point3(-2, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': EastSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastSiloControlRoomCell,
  'pos': Point3(2, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'ms',
  'parentEntId': EastSiloControlRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': EastSiloControlRoomCell,
  'pos': Point3(2, 0, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'm',
  'parentEntId': WarehouseMainFloorParent,
  'boss': 0,
  'level': 10,
  'battleCell': WarehouseMainFloorCell,
  'pos': Point3(-6, 2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': WarehouseMainFloorParent,
  'boss': 0,
  'level': 11,
  'battleCell': WarehouseMainFloorCell,
  'pos': Point3(-2, 2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'm',
  'parentEntId': WarehouseMainFloorParent,
  'boss': 0,
  'level': 10,
  'battleCell': WarehouseMainFloorCell,
  'pos': Point3(2, 2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': WarehouseMainFloorParent,
  'boss': 0,
  'level': 11,
  'battleCell': WarehouseMainFloorCell,
  'pos': Point3(6, 2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'gh',
  'parentEntId': GearRoomSet2Parent,
  'boss': 0,
  'level': 10,
  'battleCell': GearRoomSet2Cell,
  'pos': Point3(10, 10, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': GearRoomSet2Parent,
  'boss': 0,
  'level': 10,
  'battleCell': GearRoomSet2Cell,
  'pos': Point3(0, 10, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': CenterSiloOutsideBattleSet2Parent,
  'boss': 0,
  'level': 11,
  'battleCell': CenterSiloOutsideBattleSet2Cell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 8},
 {'type': 'gh',
  'parentEntId': PipeFrontParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeFrontCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': PipeFrontParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeFrontCell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': PipeFrontParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeFrontCell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': PipeFrontParent,
  'boss': 0,
  'level': 10,
  'battleCell': PipeFrontCell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': PipeBackParent,
  'boss': 0,
  'level': 11,
  'battleCell': PipeBackCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': PipeBackParent,
  'boss': 0,
  'level': 11,
  'battleCell': PipeBackCell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': PipeBackParent,
  'boss': 0,
  'level': 11,
  'battleCell': PipeBackCell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': PipeBackParent,
  'boss': 0,
  'level': 11,
  'battleCell': PipeBackCell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': LobbySet2Parent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbySet2Cell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': LobbySet2Parent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbySet2Cell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'gh',
  'parentEntId': LobbySet2Parent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbySet2Cell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'gh',
  'parentEntId': LobbySet2Parent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbySet2Cell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyRightSet1Cell,
  'pos': Point3(6, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyRightSet1Cell,
  'pos': Point3(2, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyRightSet1Cell,
  'pos': Point3(-2, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyRightSet1Cell,
  'pos': Point3(-6, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyRightSet2Cell,
  'pos': Point3(-10, -6, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyRightSet2Cell,
  'pos': Point3(-10, -2, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyRightSet2Cell,
  'pos': Point3(-10, 2, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyRightParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyRightSet2Cell,
  'pos': Point3(-10, 6, 0),
  'h': -90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyLeftSet1Cell,
  'pos': Point3(6, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyLeftSet1Cell,
  'pos': Point3(2, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyLeftSet1Cell,
  'pos': Point3(-2, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 9,
  'battleCell': LobbyLeftSet1Cell,
  'pos': Point3(-6, -20, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyLeftSet2Cell,
  'pos': Point3(10, -6, 0),
  'h': 90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyLeftSet2Cell,
  'pos': Point3(10, -2, 0),
  'h': 90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyLeftSet2Cell,
  'pos': Point3(10, 2, 0),
  'h': 90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'tf',
  'parentEntId': LobbyLeftParent,
  'boss': 0,
  'level': 10,
  'battleCell': LobbyLeftSet2Cell,
  'pos': Point3(10, 6, 0),
  'h': 90,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': WestCatwalkSet1Parent,
  'boss': 0,
  'level': 10,
  'battleCell': WestCatwalkSet1Cell,
  'pos': Point3(-5, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': WestCatwalkSet1Parent,
  'boss': 0,
  'level': 10,
  'battleCell': WestCatwalkSet1Cell,
  'pos': Point3(5, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': WarehouseLookoutParent,
  'boss': 0,
  'level': 9,
  'battleCell': WarehouseLookoutCell,
  'pos': Point3(0, -2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': WarehouseLookoutParent,
  'boss': 0,
  'level': 9,
  'battleCell': WarehouseLookoutCell,
  'pos': Point3(0, 2, 0),
  'h': 0,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': WarehouseEastParent,
  'boss': 0,
  'level': 10,
  'battleCell': WarehouseEastCell,
  'pos': Point3(-4, -2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': WarehouseEastParent,
  'boss': 0,
  'level': 12,
  'battleCell': WarehouseEastCell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': WarehouseEastParent,
  'boss': 0,
  'level': 8,
  'battleCell': WarehouseEastCell,
  'pos': Point3(4, -2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': OutsidePaintMixerParent,
  'boss': 0,
  'level': 8,
  'battleCell': OutsidePaintMixerCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 2},
 {'type': 'gh',
  'parentEntId': OutsidePaintMixerParent,
  'boss': 0,
  'level': 9,
  'battleCell': OutsidePaintMixerCell,
  'pos': Point3(-2, -2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'gh',
  'parentEntId': OutsidePaintMixerParent,
  'boss': 0,
  'level': 10,
  'battleCell': OutsidePaintMixerCell,
  'pos': Point3(2, -2, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'gh',
  'parentEntId': OutsidePaintMixerParent,
  'boss': 0,
  'level': 9,
  'battleCell': OutsidePaintMixerCell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': BoilerRoomSet2Parent,
  'boss': 0,
  'level': 9,
  'battleCell': BoilerRoomSet2Cell,
  'pos': Point3(-4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': BoilerRoomSet2Parent,
  'boss': 0,
  'level': 10,
  'battleCell': BoilerRoomSet2Cell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'gh',
  'parentEntId': BoilerRoomSet2Parent,
  'boss': 0,
  'level': 9,
  'battleCell': BoilerRoomSet2Cell,
  'pos': Point3(4, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': OutsidePipeRoomParent,
  'boss': 0,
  'level': 11,
  'battleCell': OutsidePipeRoomCell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'gh',
  'parentEntId': OutsidePipeRoomParent,
  'boss': 0,
  'level': 8,
  'battleCell': OutsidePipeRoomCell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': OilRoomHallway1Parent,
  'boss': 0,
  'level': 10,
  'battleCell': OilRoomHallway1Cell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'gh',
  'parentEntId': OilRoomHallway2Parent,
  'boss': 0,
  'level': 11,
  'battleCell': OilRoomHallway2Cell,
  'pos': Point3(0, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': SideEntranceParent,
  'boss': 0,
  'level': 10,
  'battleCell': SideEntranceCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': SideEntranceParent,
  'boss': 0,
  'level': 11,
  'battleCell': SideEntranceCell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'ms',
  'parentEntId': SideEntranceParent,
  'boss': 0,
  'level': 11,
  'battleCell': SideEntranceCell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1,
  'revives': 0},
 {'type': 'ms',
  'parentEntId': SideEntranceParent,
  'boss': 0,
  'level': 10,
  'battleCell': SideEntranceCell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': EntranceParent,
  'boss': 0,
  'level': 9,
  'battleCell': EntranceCell,
  'pos': Point3(-6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': EntranceParent,
  'boss': 0,
  'level': 10,
  'battleCell': EntranceCell,
  'pos': Point3(-2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 0},
 {'type': 'ms',
  'parentEntId': EntranceParent,
  'boss': 0,
  'level': 9,
  'battleCell': EntranceCell,
  'pos': Point3(2, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},
 {'type': 'ms',
  'parentEntId': EntranceParent,
  'boss': 0,
  'level': 9,
  'battleCell': EntranceCell,
  'pos': Point3(6, 0, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 0,
  'revives': 1},]
ReserveCogData = [{}]
