from ElevatorConstants import *
from toontown.toonbase import ToontownGlobals


try:
    config = base.config
except:
    config = simbase.config

SuitBuildingInfo = (((1, 1), #Building created by Level 1 Cog ##Number of floors
  (1, 5), #Level range
  (6, 7), #Boss level
  (11, 13), #Number of Cogs
  (1,)), #Chance of number of floors appearing
 ((1, 2),
  (2, 6),
  (7, 8),
  (12, 14),
  (1, 1.2)),
 ((1, 3),
  (3, 7),
  (8, 9),
  (13, 15),
  (1, 1.3, 1.6)),
 ((2, 3),
  (4, 8),
  (9, 10),
  (14, 16),
  (1, 1.4, 1.8)),
 ((2, 4),
  (5, 9),
  (10, 11),
  (15, 17),
  (1, 1.6, 1.8, 2)),
 ((3, 4),
  (6, 10),
  (11, 12),
  (17, 19),
  (1, 1.6, 2, 2.4)),
 ((3, 5),
  (7, 11),
  (12, 12),
  (19, 23),
  (1, 1.6, 1.8, 2.2, 2.4)),
 ((4, 5),
  (8, 11),
  (12, 12),
  (21, 27),
  (1, 1.8, 2.4, 3, 3.2)),
 ((4, 6), #Building created by Level 9 Cog
  (9, 12),
  (12, 12),
  (23, 31),
  (1.4, 1.8, 2.6, 3.4, 4, 4.6)),
 ((5, 5),
  (11, 12),
  (12, 12),
  (25, 35),
  (1.5, 1.9, 2.7, 3.5, 4.1)),
 ((5, 6),
  (9, 12),
  (13, 13),
  (29, 38),
  (1.7, 2.1, 2.9, 3.7, 4.3, 4.9)),
 ((5, 7),
  (10, 13),
  (13, 13),
  (34, 45),
  (2, 2.4, 3.2, 4, 4.6, 5.2, 6)),
 ((6, 6),
  (9, 13),
  (14, 14),
  (38, 50),
  (2.4, 2.8, 3.6, 4.4, 5, 5.6)),
 ((6, 7),
  (11, 14),
  (14, 14),
  (43, 56),
  (2.9, 3.2, 4.1, 4.9, 5.5, 6.1, 6.9)),
 ((7, 7),
  (12, 14),
  (15, 15),
  (50, 65),
  (3.5, 3.8, 4.7, 5.5, 6.1, 6.7, 7.5)),
 ((1, 1), #VP Round 1
  (6, 10),
  (10, 10),
  (67, 67),
  (1, 1, 1, 1, 1)),
 ((1, 1), #VP Round 2
  (10, 12),
  (12, 12),
  (100, 100),
  (1, 1, 1, 1, 1)),
 ((1, 1), #CFO Cogs
  (8, 13),
  (13, 13),
  (100, 100),
  (1, 1, 1, 1, 1)),
 ((1, 1), #CFO Skelecogs/Round 2
  (8, 13),
  (13, 13),
  (150, 150),
  (1, 1, 1, 1, 1)),
 ((1, 1), #CJ
  (10, 14),
  (14, 14),
  (275, 275),
  (1, 1, 1, 1, 1)),
 ((1, 1), #CEO Round 1
  (12, 15),
  (15, 15),
  (206, 206),
  (1, 1, 1, 1, 1),
  (1,)),
 ((1, 1), #Unknown
  (1, 5),
  (5, 5),
  (33, 33),
  (1, 1, 1, 1, 1)),
 ((1, 1), #Unknown
  (4, 5),
  (5, 5),
  (50, 50),
  (1, 1, 1, 1, 1)),
 ((1, 1), #CEO Round 2
  (13, 15),
  (15, 15),
  (206, 206),
  (1, 1, 1, 1, 1),
  (1,)))
SUIT_BLDG_INFO_FLOORS = 0
SUIT_BLDG_INFO_SUIT_LVLS = 1
SUIT_BLDG_INFO_BOSS_LVLS = 2
SUIT_BLDG_INFO_LVL_POOL = 3
SUIT_BLDG_INFO_LVL_POOL_MULTS = 4
SUIT_BLDG_INFO_REVIVES = 5
VICTORY_RUN_TIME = ElevatorData[ELEVATOR_NORMAL]['openTime'] + TOON_VICTORY_EXIT_TIME
TO_TOON_BLDG_TIME = 8
VICTORY_SEQUENCE_TIME = VICTORY_RUN_TIME + TO_TOON_BLDG_TIME
CLEAR_OUT_TOON_BLDG_TIME = 4
TO_SUIT_BLDG_TIME = 8

buildingMinMax = {
    ToontownGlobals.SillyStreet: [config.GetInt('silly-street-building-min', 0),
                                  config.GetInt('silly-street-building-max', 0)],
    ToontownGlobals.LoopyLane: [config.GetInt('loopy-lane-building-min', 0),
                                config.GetInt('loopy-lane-building-max', 7)],
    ToontownGlobals.PunchlinePlace: [config.GetInt('punchline-place-building-min', 0),
                                     config.GetInt('punchline-place-building-max', 7)],
    ToontownGlobals.BarnacleBoulevard: [config.GetInt('barnacle-boulevard-building-min', 2),
                                        config.GetInt('barnacle-boulevard-building-max', 8)],
    ToontownGlobals.SeaweedStreet: [config.GetInt('seaweed-street-building-min', 2),
                                    config.GetInt('seaweed-street-building-max', 8)],
    ToontownGlobals.LighthouseLane: [config.GetInt('lighthouse-lane-building-min', 2),
                                     config.GetInt('lighthouse-lane-building-max', 8)],
    ToontownGlobals.ElmStreet: [config.GetInt('elm-street-building-min', 4),
                                config.GetInt('elm-street-building-max', 10)],
    ToontownGlobals.MapleStreet: [config.GetInt('maple-street-building-min', 4),
                                  config.GetInt('maple-street-building-max', 10)],
    ToontownGlobals.OakStreet: [config.GetInt('oak-street-building-min', 4),
                                config.GetInt('oak-street-building-max', 10)],
    ToontownGlobals.AlderAvenue: [config.GetInt('alder-avenue-building-min', 4),
                                  config.GetInt('alder-avenue-building-max', 10)],
    ToontownGlobals.AltoAvenue: [config.GetInt('alto-avenue-building-min', 6),
                                 config.GetInt('alto-avenue-building-max', 12)],
    ToontownGlobals.BaritoneBoulevard: [config.GetInt('baritone-boulevard-building-min', 6),
                                        config.GetInt('baritone-boulevard-building-max', 12)],
    ToontownGlobals.TenorTerrace: [config.GetInt('tenor-terrace-building-min', 6),
                                   config.GetInt('tenor-terrace-building-max', 12)],
    ToontownGlobals.BassByway: [config.GetInt('bass-byway-building-min', 6),
                                config.GetInt('bass-byway-building-max', 12)],
    ToontownGlobals.WalrusWay: [config.GetInt('walrus-way-building-min', 8),
                                config.GetInt('walrus-way-building-max', 14)],
    ToontownGlobals.SleetStreet: [config.GetInt('sleet-street-building-min', 8),
                                  config.GetInt('sleet-street-building-max', 14)],
    ToontownGlobals.PolarPlace: [config.GetInt('polar-place-building-min', 8),
                                 config.GetInt('polar-place-building-max', 14)],
    ToontownGlobals.LullabyLane: [config.GetInt('lullaby-lane-building-min', 12),
                                  config.GetInt('lullaby-lane-building-max', 18)],
    ToontownGlobals.PajamaPlace: [config.GetInt('pajama-place-building-min', 12),
                                  config.GetInt('pajama-place-building-max', 18)],
    ToontownGlobals.SlumberStreet: [config.GetInt('slumber-street-building-min', 12),
                                    config.GetInt('slumber-street-building-max', 18)],
    ToontownGlobals.WhisperWay: [config.GetInt('whisper-way-building-min', 12),
                                 config.GetInt('whisper-way-building-max', 18)],                          
    ToontownGlobals.PavementPath: [config.GetInt('pavement-path-building-min', 10),
                                   config.GetInt('pavement-path-building-max', 16)],
    ToontownGlobals.BedrockBoulevard: [config.GetInt('bedrock-boulevard-building-min', 10),
                                       config.GetInt('bedrock-boulevard-building-max', 16)],
    ToontownGlobals.SawmillStreet: [config.GetInt('sawmill-street-building-min', 10),
                                    config.GetInt('sawmill-street-building-max', 16)],
    ToontownGlobals.SellbotHQ: [0, 0],
    ToontownGlobals.SellbotFactoryExt: [0, 0],
    ToontownGlobals.CashbotHQ: [0, 0],
    ToontownGlobals.LawbotHQ: [0, 0],
    ToontownGlobals.BossbotHQ: [0, 0]
}

buildingChance = {
    ToontownGlobals.SillyStreet: config.GetFloat('silly-street-building-chance', 25.0),
    ToontownGlobals.LoopyLane: config.GetFloat('loopy-lane-building-chance', 25.0),
    ToontownGlobals.PunchlinePlace: config.GetFloat('punchline-place-building-chance', 25.0),
    ToontownGlobals.BarnacleBoulevard: config.GetFloat('barnacle-boulevard-building-chance', 40.0),
    ToontownGlobals.SeaweedStreet: config.GetFloat('seaweed-street-building-chance', 40.0),
    ToontownGlobals.LighthouseLane: config.GetFloat('lighthouse-lane-building-chance', 40.0),
    ToontownGlobals.ElmStreet: config.GetFloat('elm-street-building-chance', 60.0),
    ToontownGlobals.MapleStreet: config.GetFloat('maple-street-building-chance', 60.0),
    ToontownGlobals.OakStreet: config.GetFloat('oak-street-building-chance', 60.0),
    ToontownGlobals.AlderAvenue: config.GetFloat('alder-avenue-building-chance', 60.0),
    ToontownGlobals.AltoAvenue: config.GetFloat('alto-avenue-building-chance', 70.0),
    ToontownGlobals.BaritoneBoulevard: config.GetFloat('baritone-boulevard-building-chance', 70.0),
    ToontownGlobals.TenorTerrace: config.GetFloat('tenor-terrace-building-chance', 70.0),
    ToontownGlobals.BassByway: config.GetFloat('bass-byway-building-chance', 70.0),
    ToontownGlobals.WalrusWay: config.GetFloat('walrus-way-building-chance', 80.0),
    ToontownGlobals.SleetStreet: config.GetFloat('sleet-street-building-chance', 80.0),
    ToontownGlobals.PolarPlace: config.GetFloat('polar-place-building-chance', 80.0),
    ToontownGlobals.LullabyLane: config.GetFloat('lullaby-lane-building-chance', 100.0),
    ToontownGlobals.PajamaPlace: config.GetFloat('pajama-place-building-chance', 100.0),
    ToontownGlobals.SlumberStreet: config.GetFloat('slumber-street-building-chance', 100.0),
    ToontownGlobals.WhisperWay: config.GetFloat('whisper-way-building-chance', 100.0),
    ToontownGlobals.PavementPath: config.GetFloat('pavement-path-building-chance', 90.0),
    ToontownGlobals.BedrockBoulevard: config.GetFloat('bedrock-boulevard-building-chance', 90.0),
    ToontownGlobals.SawmillStreet: config.GetFloat('sawmill-street-building-chance', 90.0),
    ToontownGlobals.SellbotHQ: 0.0,
    ToontownGlobals.SellbotFactoryExt: 0.0,
    ToontownGlobals.CashbotHQ: 0.0,
    ToontownGlobals.LawbotHQ: 0.0,
    ToontownGlobals.BossbotHQ: 0.0
}
