uberdogs:
    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: ChatAgent
      id: 4681
      anonymous: false

    - class: FriendManager
      id: 4501
      anonymous: false

    - class: TTSFriendsManager
      id: 4666
      anonymous: false

    - class: GlobalPartyManager
      id: 4477
      anonymous: false
